version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 &&
             python manage.py search_index --create -f &&
             manage.py search_index --populate -f"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file: djangoProject/.env
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: PostgresDockerfile
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: djangoProject/.env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.16
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.16
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  postgres_data: