name: Deploy to Dev Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
  DEBUG: ${{secrets.DEBUG}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_NAME: ${{secrets.POSTGRES_NAME}}
  POSTGRES_USER: ${{secrets.POSTGRES_USER}}
  POSTGRES_DB: ${{secrets.POSTGRES_DB}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: /var/www/ci.dev/
          EXCLUDE: ".env.dev"

    - name: Rebuild and restart containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/ci.dev/
          docker-compose -f docker-compose-ci.yml down
          docker-compose -f docker-compose-ci.yml up -d --build
          docker-compose -f docker-compose-ci.yml exec -T main python manage.py makemigrations
          docker-compose -f docker-compose-ci.yml exec -T main python manage.py migrate
